<?php

declare(strict_types=1);

namespace Drupal\content_preparation_wizard\Model;

use Drupal\content_preparation_wizard\Enum\PlanStatus;

/**
 * Immutable value object representing a content plan.
 *
 * A content plan is generated by AI based on processed documents and
 * contains the structured outline for creating Canvas pages.
 */
final class ContentPlan {

  /**
   * Constructs a ContentPlan object.
   *
   * @param string $id
   *   Unique identifier for this plan.
   * @param string $title
   *   The suggested title for the content.
   * @param string $summary
   *   A summary of the planned content.
   * @param array<\Drupal\content_preparation_wizard\Model\PlanSection> $sections
   *   The planned content sections.
   * @param string $targetAudience
   *   The intended target audience.
   * @param int $estimatedReadTime
   *   Estimated reading time in minutes.
   * @param \DateTimeImmutable $generatedAt
   *   When this plan was generated.
   * @param \Drupal\content_preparation_wizard\Enum\PlanStatus $status
   *   The current status of the plan.
   * @param array<\Drupal\content_preparation_wizard\Model\RefinementEntry> $refinementHistory
   *   History of refinements made to this plan.
   * @param array<string> $sourceDocumentIds
   *   IDs of the source ProcessedDocuments.
   * @param string|null $templateId
   *   The AI template ID used for generation.
   */
  public function __construct(
    public readonly string $id,
    public readonly string $title,
    public readonly string $summary,
    public readonly array $sections,
    public readonly string $targetAudience,
    public readonly int $estimatedReadTime,
    public readonly \DateTimeImmutable $generatedAt,
    public readonly PlanStatus $status = PlanStatus::DRAFT,
    public readonly array $refinementHistory = [],
    public readonly array $sourceDocumentIds = [],
    public readonly ?string $templateId = NULL,
  ) {}

  /**
   * Creates a new instance with an updated status.
   *
   * @param \Drupal\content_preparation_wizard\Enum\PlanStatus $status
   *   The new status.
   *
   * @return self
   *   A new instance with the updated status.
   */
  public function withStatus(PlanStatus $status): self {
    return new self(
      $this->id,
      $this->title,
      $this->summary,
      $this->sections,
      $this->targetAudience,
      $this->estimatedReadTime,
      $this->generatedAt,
      $status,
      $this->refinementHistory,
      $this->sourceDocumentIds,
      $this->templateId,
    );
  }

  /**
   * Creates a new instance with an added refinement entry.
   *
   * @param \Drupal\content_preparation_wizard\Model\RefinementEntry $entry
   *   The refinement entry to add.
   *
   * @return self
   *   A new instance with the added refinement.
   */
  public function withRefinement(RefinementEntry $entry): self {
    $history = $this->refinementHistory;
    $history[] = $entry;

    return new self(
      $this->id,
      $this->title,
      $this->summary,
      $this->sections,
      $this->targetAudience,
      $this->estimatedReadTime,
      $this->generatedAt,
      $this->status,
      $history,
      $this->sourceDocumentIds,
      $this->templateId,
    );
  }

  /**
   * Creates a new instance with updated sections.
   *
   * @param array<\Drupal\content_preparation_wizard\Model\PlanSection> $sections
   *   The new sections.
   *
   * @return self
   *   A new instance with updated sections.
   */
  public function withSections(array $sections): self {
    return new self(
      $this->id,
      $this->title,
      $this->summary,
      $sections,
      $this->targetAudience,
      $this->estimatedReadTime,
      $this->generatedAt,
      $this->status,
      $this->refinementHistory,
      $this->sourceDocumentIds,
      $this->templateId,
    );
  }

  /**
   * Creates a new instance with an updated title.
   *
   * @param string $title
   *   The new title.
   *
   * @return self
   *   A new instance with the updated title.
   */
  public function withTitle(string $title): self {
    return new self(
      $this->id,
      $title,
      $this->summary,
      $this->sections,
      $this->targetAudience,
      $this->estimatedReadTime,
      $this->generatedAt,
      $this->status,
      $this->refinementHistory,
      $this->sourceDocumentIds,
      $this->templateId,
    );
  }

  /**
   * Gets the total section count including nested sections.
   *
   * @return int
   *   The total number of sections.
   */
  public function getTotalSectionCount(): int {
    $count = 0;
    foreach ($this->sections as $section) {
      $count += count($section->flatten());
    }
    return $count;
  }

  /**
   * Gets the total word count across all sections.
   *
   * @return int
   *   The total word count.
   */
  public function getTotalWordCount(): int {
    $count = 0;
    foreach ($this->sections as $section) {
      $count += $section->getTotalWordCount();
    }
    return $count;
  }

  /**
   * Gets the number of refinements made.
   *
   * @return int
   *   The refinement count.
   */
  public function getRefinementCount(): int {
    return count($this->refinementHistory);
  }

  /**
   * Gets the most recent refinement entry.
   *
   * @return \Drupal\content_preparation_wizard\Model\RefinementEntry|null
   *   The most recent refinement or NULL if none.
   */
  public function getLastRefinement(): ?RefinementEntry {
    if (empty($this->refinementHistory)) {
      return NULL;
    }
    return end($this->refinementHistory);
  }

  /**
   * Gets a section by its ID.
   *
   * @param string $sectionId
   *   The section ID to find.
   *
   * @return \Drupal\content_preparation_wizard\Model\PlanSection|null
   *   The section or NULL if not found.
   */
  public function getSection(string $sectionId): ?PlanSection {
    foreach ($this->sections as $section) {
      foreach ($section->flatten() as $flatSection) {
        if ($flatSection->id === $sectionId) {
          return $flatSection;
        }
      }
    }
    return NULL;
  }

  /**
   * Gets a suggested URL path based on the title.
   *
   * @return string
   *   A URL-friendly path.
   */
  public function getSuggestedPath(): string {
    $path = strtolower($this->title);
    $path = preg_replace('/[^a-z0-9\s-]/', '', $path);
    $path = preg_replace('/[\s_]+/', '-', $path);
    $path = trim($path, '-');
    return $path;
  }

  /**
   * Converts the plan to an array for serialization.
   *
   * @return array<string, mixed>
   *   The plan as an associative array.
   */
  public function toArray(): array {
    return [
      'id' => $this->id,
      'title' => $this->title,
      'summary' => $this->summary,
      'sections' => array_map(
        fn(PlanSection $section): array => $section->toArray(),
        $this->sections
      ),
      'target_audience' => $this->targetAudience,
      'estimated_read_time' => $this->estimatedReadTime,
      'generated_at' => $this->generatedAt->format(\DateTimeInterface::RFC3339),
      'status' => $this->status->value,
      'refinement_history' => array_map(
        fn(RefinementEntry $entry): array => $entry->toArray(),
        $this->refinementHistory
      ),
      'source_document_ids' => $this->sourceDocumentIds,
      'template_id' => $this->templateId,
      'total_section_count' => $this->getTotalSectionCount(),
      'total_word_count' => $this->getTotalWordCount(),
    ];
  }

  /**
   * Creates a ContentPlan instance from an array.
   *
   * @param array<string, mixed> $data
   *   The data array from serialization.
   *
   * @return self
   *   A new ContentPlan instance.
   *
   * @throws \InvalidArgumentException
   *   If required data is missing or invalid.
   */
  public static function fromArray(array $data): self {
    $requiredFields = ['id', 'title', 'summary', 'sections', 'target_audience', 'estimated_read_time', 'generated_at'];
    foreach ($requiredFields as $field) {
      if (!isset($data[$field])) {
        throw new \InvalidArgumentException("Missing required field: {$field}");
      }
    }

    $status = PlanStatus::tryFrom($data['status'] ?? 'draft');
    if ($status === NULL) {
      $status = PlanStatus::DRAFT;
    }

    $sections = [];
    foreach ($data['sections'] as $sectionData) {
      $sections[] = PlanSection::fromArray($sectionData);
    }

    $refinementHistory = [];
    if (!empty($data['refinement_history'])) {
      foreach ($data['refinement_history'] as $entryData) {
        $refinementHistory[] = RefinementEntry::fromArray($entryData);
      }
    }

    return new self(
      id: $data['id'],
      title: $data['title'],
      summary: $data['summary'],
      sections: $sections,
      targetAudience: $data['target_audience'],
      estimatedReadTime: (int) $data['estimated_read_time'],
      generatedAt: new \DateTimeImmutable($data['generated_at']),
      status: $status,
      refinementHistory: $refinementHistory,
      sourceDocumentIds: $data['source_document_ids'] ?? [],
      templateId: $data['template_id'] ?? NULL,
    );
  }

  /**
   * Creates a new ContentPlan with a generated unique ID.
   *
   * @param string $title
   *   The plan title.
   * @param string $summary
   *   The plan summary.
   * @param array<\Drupal\content_preparation_wizard\Model\PlanSection> $sections
   *   The plan sections.
   * @param string $targetAudience
   *   The target audience.
   * @param int $estimatedReadTime
   *   Estimated reading time.
   * @param array<string> $sourceDocumentIds
   *   Source document IDs.
   * @param string|null $templateId
   *   The template ID used.
   *
   * @return self
   *   A new ContentPlan instance.
   */
  public static function create(
    string $title,
    string $summary,
    array $sections,
    string $targetAudience,
    int $estimatedReadTime,
    array $sourceDocumentIds = [],
    ?string $templateId = NULL,
  ): self {
    return new self(
      id: 'plan_' . bin2hex(random_bytes(8)),
      title: $title,
      summary: $summary,
      sections: $sections,
      targetAudience: $targetAudience,
      estimatedReadTime: $estimatedReadTime,
      generatedAt: new \DateTimeImmutable(),
      status: PlanStatus::DRAFT,
      refinementHistory: [],
      sourceDocumentIds: $sourceDocumentIds,
      templateId: $templateId,
    );
  }

}
